### ISSUE TITLE
transcriptomeDB instructions missing

### ISSUE THREAD

**Issue by tbrittoborges** [areyesq89/HumanTissuesDEU#1]
Excellent work in the paper. I would like to experiment with your plotSashimi function, but I can't find the instructions to produce the transcriptomeDB object. Could you please point me out where to find these instructions?

**Comment by areyesq89** [comment]
Hi @tbrittoborges. Thanks for your interest in this paper! 

The help pages of the package GenomicFeatures contain instructions on how to create `transcriptDb` objects. I like a lot the function `makeTxDbFromGFF`, which inputs a gtf file and gives back a `transcriptDb` object. 

Note that my plotSashimi function is just a wrapper that calls functions of the [Gviz](https://bioconductor.org/packages/release/bioc/html/Gviz.html) Bioconductor package. It might be easer to use directly the functions from Gviz.

**Comment by tbrittoborges** [comment]
Thank you for the prompt response, I will check the Gviz package.
All the best,
Thiago
